// VueProjectarticles/src/components/ArticleUpdateComponent.vue


<template>
  <div>
    <SliderComponent SliderClass="slider-small"></SliderComponent>

    <div class="center">
      <section id="content">
        <h1 class="subheader">Editar Artículo</h1>

        <form class="mid-form" v-if="id != null" @submit="(e) => Submit(e)">
          <div class="form-group">
            <input
              type="file"
              name="titulo"
              id="InputFile"
              @change="(e) => eventImage(e)"
            />
            <p
              @click="() => eventImage(null)"
              style="cursor: pointer"
              v-if="previewImageUrl != null || firstImage"
            >
              X
            </p>

            <div class="image-wrap image-all">
              <img :src="previewImageUrl" v-if="previewImageUrl != null" />
              <img
                :src="urlImage + id + extImage"
                v-if="previewImageUrl == null && firstImage"
              />
            </div>
          </div>

          <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" name="titulo" v-model="title" required/>
          </div>

          <div class="form-group">
            <label for="content">Contenido</label>
            <textarea rows="3" type="text" name="content" v-model="content" required/>
          </div>

          <div class="clearfix"></div>

          <input type="submit" value="Editar" class="btn btn-success" />
        </form>
      </section>
    </div>

    <SideBarComponent></SideBarComponent>

     <div class="clearfix"></div>
  </div>
</template>


<script>
import SliderComponent from "./SliderComponent.vue";
import SideBarComponent from "./SideBarComponent.vue";
import Global from "../Global.js";
import Services from "../Services.js";
import swal from "sweetalert";
import ArticleModel from "../models/ArticleModel.js";

var global = new Global();
var services = new Services();
var AModel = new ArticleModel();

export default {
  name: "ArticleUpdateComponent",
  components: {
    SliderComponent,
    SideBarComponent,
  },

  data() {
    return {
      extImage: ".jpg" + global.random(),
      urlImage: global.urlImage,

      eventImageFile: null,
      previewImageUrl: null,
      firstImage: true,
      updateImage: false,

      id: null,
      title: null,
      content: null,
      date: null,
      image: null,
    };
  },

  methods: {
    async getArticle() {
      const res = await services.getById(
        global.urlBase + "articles/null/" + this.$route.params.id
      );
      if (res != null && res != []) {
        this.id = res.data.articles[0]._id;
        this.title = res.data.articles[0].title;
        this.content = res.data.articles[0].content;
        this.date = res.data.articles[0].date;
        this.image = res.data.articles[0].image;
      }
    },

    async eventImage(event) {
      this.eventImageFile = null;
      this.previewImageUrl = null;
      this.firstImage = false;
      this.updateImage = false;

      if (event != null) {
        this.eventImageFile = event.target.files[0];
        this.previewImageUrl = await global.ImagePreview(this.eventImageFile);
      } else {
        document.getElementById("InputFile").value = "";
      }

    },

    async UpdateArticle() {
      AModel._id = this.id;
      AModel.title = this.title;
      AModel.content = this.content;
      AModel.date = this.date;
      AModel.image = this.image;

        var updateImageBool = false;
          if (this.previewImageUrl != null) {
            updateImageBool = true;
          }
          if (this.previewImageUrl == null && this.firstImage == false) {
            updateImageBool = true;
          }

        

      const res = await services.update(global.urlBase + "article/"+updateImageBool, AModel);

      if (res != null && res != []) {

        if (res.data.status == "success") {

          if (updateImageBool) {
            const resImage = await global.uploadImage(
              global.urlBase + "article-image/",
              this.eventImageFile,
              res.data.article._id
            );

             
            if (resImage != null) {

              if (resImage != "success") {
                          swal(
                  "¡Algo salió mal al actualizar la imágen!",
                  "OK",
                  "warning"
                );             
              }
            }
          }


                 swal("¡Artículo actualizado!", "OK", "success");
                 this.$router.push("/articulo/" + this.id);
   
        } else {
          swal("¡Algo salió mal!", "OK", "warning");
        }
      }
    },


  async Submit(e){
       e.preventDefault();
      await  this.UpdateArticle();
    }

  },

  async mounted() {
    await this.getArticle();
  },
};
</script>

// AngularProjectArticles/src/app/components/article-update/article-update.component.ts
import { Component, Input, OnInit, Output } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Article } from '../../models/article';
import { ArticleService } from '../../services/articles.services';
import { SweetAlert } from 'sweetalert/typings/core';
import { stringify } from 'querystring';
const swal: SweetAlert = require('sweetalert');
import { Global } from '../../services/global';

@Component({
  selector: 'app-article-update',
  templateUrl: './article-update.component.html',
  styleUrls: ['./article-update.component.css'],

  providers: [ArticleService]
})
export class ArticleUpdateComponent implements OnInit {

  public article: Article;
  public eventImageProp: any;
  public g = new Global();

  //preview image
  public previewUrl: any = null;
  public FirstImage: any;
  public urlImage : string;

  constructor(private http: ArticleService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.article = new Article('', '', '', '', Date.now);
    this.eventImageProp = null;
    this.FirstImage = true;

    this.getImage();
  }

  ngOnInit(): void {

    this.route.params.subscribe(params => {

      let id = params['id'];

      this.http.getArticles('null', id).subscribe(

        response => {

          if (response.articles) {
            this.article._id = response.articles[0]._id;
            this.article.title = response.articles[0].title;
            this.article.content = response.articles[0].content;
            this.article.image = response.articles[0]._id + '.jpg';
          } else {
            this.article = null;
          }

        },
        error => {
          this.article = null;
        }

      )

    });

  }



  onSubmit() {

    var updateImage = false;

    if (this.eventImageProp == null && this.FirstImage == true) {
      updateImage = false;
    }

    if (this.eventImageProp != null) {
      updateImage = true;
    }

    //Boton X Image
    if (this.eventImageProp == null && this.FirstImage == false) {
      updateImage = true;
    }

  
    this.http.update(this.article, updateImage).subscribe(

      response => {
        if (response.status == 'success') {
          swal("Mensaje", "¡Artículo Actualizado! ", "success");

          if (this.eventImageProp != null) {
            this.uploadImage(this.eventImageProp, response.article._id);
          }

          this.router.navigate(['/blog/articulo', response.article._id]);
        } else {
          swal("Algo salió mal", "¡No se actualizó el artículo!", "error");

        }
      },

      error => {
        swal("Algo salió mal", "¡No se actualizó el artículo! " + JSON.stringify(error), "error");
      }

    )


  }

  async eventImage(event) {
    this.FirstImage = false;
    this.eventImageProp = null;
    this.previewUrl = null;

    if (event != null) {
      this.eventImageProp = event;
      this.previewUrl = await this.g.ImagePreview(event);
    }

  }


  uploadImage(event, id) {

    this.http.uploadImage(event, id).subscribe(

      response => {
        if (response.status == "error") {
          swal("Algo salió mal", "¡No se guardó la imágen! RESPONSE " + JSON.stringify(response), "error");
        }
      },
      error => {
        swal("Algo salió mal", "¡No se guardó la imágen! ERROR " + JSON.stringify(error), "error");
      }

    )
  }


  getImage(){
    this.route.params.subscribe( params => {
      var id = params['id'];
      //se le pone ?+Math.random ya que el navegador guarda la imágen en 
      // caché y no se actualiza al actualizar (valga la redundancia) la imágen
      this.urlImage = this.g.getImage(id);
    } );
    
   }
}

<app-slider
[size]="'small'"
[nombre]="'Edita El Artíclo de Freezer!!'"
></app-slider>

<div class="center">
    <section id="content">

        <h1 class="subheader">Editar Articulo</h1>

        <form class="mid-form" #articleForm="ngForm" (ngSubmit)="onSubmit()" enctype="multipart/form-data" type="POST">
          
        <div class="form-group">   

          <input type="file" accept="image/*" (change)="eventImage($event);" >
          <div (click)="eventImage(null); InputFile.value = ''; FirstImage = false;" *ngIf="previewUrl != null || FirstImage" >X</div>
            

          <div class="article-detail" *ngIf="previewUrl == null && !FirstImage" >
           Sin imágen
        </div>

          <div class="article-detail" *ngIf="previewUrl == null && FirstImage " >
                <div class="image-wrap image-all">
                    <img src="{{urlImage}}" />     
                </div>     
    
            </div>  


            <div class="article-detail" *ngIf="previewUrl != null">
                <div class="image-wrap image-all">
                    <img src="{{previewUrl}}" />                 
                </div>     
    
            </div>  
            
        </div>  
          
          
            <div class="form-group">
                <label for="nombre">Titulo</label>
                <input type="text" name="titulo" #titulo="ngModel" [(ngModel)]="article.title" required/>
           
                <small *ngIf="!titulo.valid && titulo.touched">
                    El titulo es requerido
                </small>

            </div>

            <div class="form-group">
                <label for="apellidos">Contenido</label>
                <textarea type="text" name="contenido" #contenido="ngModel"  [(ngModel)]="article.content" rows="3" required></textarea>
           
                <small *ngIf="!contenido.valid && contenido.touched">
                    El contenido son requeridos
                </small>

            </div>

            <div class="clearfix"></div>

            <input type="submit" value="Actualizar" class="btn btn-success" [disabled]="articleForm.invalid"/>

       </form>

    </section>

    <app-sidebar></app-sidebar>

</div>
