// VueProjectarticles/src/components/ArticleComponent.vue


<template>
  <div>
    <SliderComponent SliderClass="slider-small"></SliderComponent>

    <div class="center">
      <section id="content">
        <div id="articles" v-if="articles">
          <article
            class="article-item article-detail"
            v-for="article in articles"
            :key="article._id"
          >
            <div class="image-wrap">
              <img
                :src="urlImage + article._id + extImage + random"
                :alt="article.title"
              />
            </div>

            <h1 class="subheader">{{ article.title }}</h1>
            <span class="date">
              {{ article.date | moment("from", "now") }}
            </span>
            <p>
              {{ article.content }}
            </p>

            <button class="btn btn-warning" @click="ToEdit(article._id)">Editar</button>
            <button class="btn btn-danger" @click="Delete(article._id)">
              Eliminar
            </button>

          </article>

          <!--AÑADIR ARTICULOS VIA JS-->
        </div>
      </section>
    </div>

    <SideBarComponent></SideBarComponent>

 <div class="clearfix"></div>
  </div>
</template>



<script>
import SliderComponent from "./SliderComponent";
import SideBarComponent from "./SideBarComponent";
import Global from "../Global.js";
import Services from "../Services.js";
import swal from "sweetalert";

var global = new Global();
var services = new Services();

export default {
  name: "Article",
  components: {
    SliderComponent,
    SideBarComponent,
  },

  data() {
    return {
      articles: [],
      urlImage: global.urlImage,
      extImage: ".jpg",
      random: global.random(),
    };
  },

  async mounted() {
    await this.getArticles();
  },

  methods: {
    async getArticles() {
      const res = await services.getById(
        global.urlBase + "articles/null/" + this.$route.params.id
      );

      if (res != null) {
        this.articles = res.data.articles;
      }
    },

    ToEdit(id){
       this.$router.push('/actualizar-articulo/'+id);
    },

    async Delete(id) {
      swal({
        title: "¿Estás segur@ de eliminar el artículo?",
        text: "Una vez eliminado no podrá recuperarse!!",
        icon: "warning",
        buttons: ["Cancelar", "OK"],
        dangerMode: true,
      }).then(async (willDelete)  => {
        if (willDelete) {

          const res = await services.delete(global.urlBase + "article/" + id);
          if (res != null && res != []) {
            if (res.data.status == "success") {
              swal("El artículo ha sido eliminado!!", {
                icon: "success",
              });
              this.$router.push('/blog/');
            }else{
                 swal("El artículo ha sido eliminado!!", {
                icon: "warning",
              });
            }
          }
        } else {
          swal("Tranquilo el artículo no se eliminó :)");
        }
      });
    },
  },
};
</script>

// AngularProjectArticles/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { ArticleService } from '../../services/articles.services';
import { Article } from '../../models/article';
import { SweetAlert } from 'sweetalert/typings/core';
const swal: SweetAlert = require('sweetalert');
import {Global} from '../../services/global';
import { timingSafeEqual } from 'crypto';
import { threadId } from 'worker_threads';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],

  providers:[ ArticleService ]
})
export class ArticleComponent implements OnInit {

  public article : Article[];
  public url : string;
  public urlImage : string;

  constructor(
    private _articleService : ArticleService,
    private _router : Router,
    private _route : ActivatedRoute
  ) {
    var g = new Global();
    this.url = g.url();
    this.getImage();
   }

  ngOnInit(): void {

    this._route.params.subscribe( params => {

       var id = params['id'];
      
       this._articleService.getArticles(false, id).subscribe( 

        response=>{
  
          if(response.articles){
           
            this.article = response.articles;
    
          }else{
            this.article = [];
          }
        
        }, 
        error=>{
           console.log(error);
           this.article = [];
        }
  
       );

     

    } );


  }


  Delete(){
    
    swal({
      title: "¿Estás seguro(a) de eliminar este artículo?",
      text: "¡Una vez eliminado no se podrá recuperar!",
      icon: "warning",
      buttons: ['Cancelar', 'Confirmar']
    })
    .then((willDelete) => {
      if (willDelete) {

        this._articleService.delete(this.article[0]._id).subscribe(
           
          response=>{
               if(response.status == "success"){
                swal("¡El artículo se ha eliminado!", {
                  icon: "success",
                });
                this._router.navigate(['/blog']);
               }else{
                swal("Algo salió mal", "¡No se pudo eliminar el artículo!", "error");
               }
          },

          error=>{
            swal("Algo salió mal", "¡No se eliminar el artículo!", "error");
          }
          
        )

      } else {
        swal("Ok el artículo no se eliminó :)");
      }
    });

  }



  getImage(){
    this._route.params.subscribe( params => {
      var id = params['id'];
      //se le pone ?+Math.random ya que el navegador guarda la imágen en 
      // caché y no se actualiza al actualizar (valga la redundancia) la imágen
      this.urlImage = this.url+'get-image/'+id+'.jpg?'+Math.random();
    } );
    
   }



}
